// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ParseCSV(arg1) {
  return window['go']['main']['App']['ParseCSV'](arg1);
}
