// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenFile():Promise<main.ParseResult>;

export function ParseCSV(arg1:string):Promise<main.ParseResult>;
